Docker 2
Otus-DevOps-2023-03/ByteBattler_microservices pull request #1
Opened 2023-06-06 15:17 UTC by ByteBattler

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Установлен Docker
 - Сконфигурирован Docker-machine
 - Запущено веб-приложение

## Как запустить проект:
 - Запустить команду docker run --name reddit -d -p 9292:9292 atatarintsev/otus-reddit:1.0

## Как проверить работоспособность:
 - Например, перейти по ссылке http://<адрес>:9292

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-06-07 19:43 UTC, mrgreyves requested changes
Здравствуйте!)
У вас куда то пропали тесты
Их можно взять из вашего инфра репозитория
Нужно добавить

2023-06-09 14:10 UTC, ByteBattler commented
Здравствуйте! Т.к. задание по установке Travis CI было не обязательным, его я не делал. Подскажите пожалуйста, где взять инфу по настройке?

2023-06-09 14:58 UTC, ByteBattler commented
Получилось настроить:)

2023-06-13 14:41 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Все задания выполнены корректно, дз принимаю ^_^

2023-06-14 12:14 UTC, merged